### ISSUE TITLE
DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: transformSource

### ISSUE THREAD

**Issue by OzzyCzech** [node-loader/node-loader-babel#5]
Hi there,

I am getting obsolete warning since nodejs v17.x and loader not working under that version. Seems that loaders has changed API.

https://nodejs.org/api/esm.html#loadurl-context-defaultload

Note: In a previous version of this API, this was split across 3 separate, now deprecated, hooks (getFormat, getSource, and transformSource).

**Comment by OzzyCzech** [comment]
https://github.com/giltayar/babel-register-esm/blob/eeb9a79c7646c7ee38e0cbb64de85b0548057076/src/babel-register-esm.js#L135

**Comment by internettrans** [comment]
Resolved in #6 and released in https://github.com/node-loader/node-loader-babel/releases/tag/v2.0.0
